name: Build Project for PR
on:

  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile with Maven
      run: mvn -B clean package -DskipTests

    - name: Build Docker image for payment-service-app
      run: docker build -t payment-service-app:latest ./payment-service-app

    - name: Build Docker image for xpayment-adapter-app
      run: docker build -t xpayment-adapter-app:latest ./xpayment-adapter-app

    - name: Set up Docker Compose
      run: docker compose up -d

    - name: Run tests
      run: mvn -B test

    - name: Run Checkstyle for payment-service-app
      working-directory: ./payment-service-app
      run: mvn -B checkstyle:check
